version: '3.9'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - influxdb

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devices_db
    ports:
      - "5432:5432"

  influxdb:
    image: influxdb:2.0
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: org
      DOCKER_INFLUXDB_INIT_BUCKET: devices
    ports:
      - "8086:8086"

  localstack:
    image: localstack/localstack
    environment:
      SERVICES: lambda
    ports:
      - "4566:4566"